---
name: "Frenck's Home Assistant Add-on Linter"
description: 🚀 Frenck's GitHub Action for linting Home Assistant Add-ons.
author: frenck

branding:
  color: red
  icon: thumbs-up

inputs:
  path:
    description: Path to the add-on configuration (where config.json is)
    required: true
  community:
    description: Enable Home Assistant Community Add-ons mode, with specific checks
    default: "false"
    required: false

runs:
  using: "docker"
  image: "src/Dockerfile"
